### ISSUE TITLE
Adjust notes with normative content

### ISSUE THREAD

**Issue by tidoust** [w3c/remote-playback#101]
Notes in specs are by nature informative and as such should not contain normative statements. Notes in the current draft of the Remote Playback API that contain normative statements should either be adjusted to remain informative, or the content should be turned into real normative statements, to remove all ambiguity on the informative/normative nature of the text.

Notes that need some update:

- At the end of [§6.2.1.3](https://w3c.github.io/remote-playback/#getting-the-remote-playback-devices-availability-information). Suggestion would be to simply make the "should not" an informative one.
- Note in [§6.2.2](https://w3c.github.io/remote-playback/#prompt-user-for-changing-remote-playback-state) that states "for example it MAY show the user a dialog". Suggestion would be to make that "may" an informative one.
- Notes at the end of [§6.2.4](https://w3c.github.io/remote-playback/#establishing-a-connection-with-a-remote-playback-device). Here I would rather drop the "note" tag to make the text normative. Both normative statements sound good and are (manually) testable.
- Note at the end of [§6.2.7](https://w3c.github.io/remote-playback/#disconnecting-from-a-remote-playback-device) about abrupt disconnection. I guess I would make the "should" an informative one as it's not going to be easy to test the notion of "abrupt disconnection".

**Comment by anssiko** [comment]
Fixed with #102
