### ISSUE TITLE
Restrict the API to Secure Contexts or discuss the decision in Security Considerations

### ISSUE THREAD

**Issue by jyasskin** [w3c/remote-playback#107]
The web platform restricts most new features, and especially ones that involve asking the user a question, to [Secure Contexts](https://w3c.github.io/webappsec-secure-contexts/#integration-idl). It looks like Remote Playback [does](https://w3c.github.io/remote-playback/#user-interface-guidelines) intend to show the user an origin, which means it ought to only be available when that origin is known to be the source of the content.

If there are [reasons](https://groups.google.com/a/chromium.org/d/topic/blink-dev/lumj0lVdtHA/discussion) to provide the API to non-secure contexts anyway, they should show up in the Security Considerations section so that security reviewers know to think about them.

**Comment by mounirlamouri** [comment]
I will happily update the security considerations later. I believe that we shouldn't limit this to secure origins as one of the goal is to expose UA features available in native controls and they are not limited to secure origins.
