### ISSUE TITLE
Rephrase normative statement in security and privacy consideration section

### ISSUE THREAD

**Issue by tidoust** [w3c/remote-playback#109]
The section is non-normative, so should not contain any normative statement. There is one remaining in [section 7.1](https://w3c.github.io/remote-playback/#personally-identifiable-information)

s/The user agent SHOULD NOT monitor the list of available remote playback devices/The user agent should not monitor the list of available remote playback devices/

**Comment by markafoltz** [comment]
Fixed by https://github.com/w3c/remote-playback/commit/df201f5c7df26f2cddb8927724bf5d2665fed4af.
