### ISSUE TITLE
[Chrome 64] The RemotePlayback API is disabled on this platform

### ISSUE THREAD

**Issue by Mathieu-R** [w3c/remote-playback#116]
Hello,

When I try to use the _Remote Playback API_ on **Chrome 64**, I get this error message as I call `myAudioElement.remote.prompt()` : 

```
Uncaught (in promise) DOMException: The RemotePlayback API is disabled on this platform.
```

I did not find any information so have you more information about that ?
I'm still able to cast for example on google play music so I'm a little bit confused.

Thanks for your help.

**Comment by mounirlamouri** [comment]
Which platform are you testing this on? The Remote Playback API is only expected to work on Chrome for Android. Desktop platforms only support the Presentation API at the moment.

**Comment by Mathieu-R** [comment]
Oh well, I tried on Chrome Desktop, so I could chromecast a music with the presentation api ?

**Comment by markafoltz** [comment]
@mounirlamouri Is that really the right behavior for Chrome desktop - it seems like it should throw NotSupportedError instead? 

@Mathieu-R Yes, you can use the Presentation API on desktop Chrome to present any URL on Chromecast.  Here are some sample apps that may help you:

- https://googlechrome.github.io/samples/presentation-api/
- https://github.com/GoogleChromeLabs/presentation-api-samples/tree/master/photowall

Unfortunately we don't support the full Presentation API on Chrome for Android yet.

We are always looking for developer feedback to help refine these APIs, so feel free to reach out if you have any questions or feedback.

Thanks!

**Comment by mounirlamouri** [comment]
@mfoltzgoogle it does fire a `NotSupportedError`. The message @Mathieu-R quoted is the error message which is different from the error type.

I'm going to close this as it's more an implementation feedback than a spec feedback.
