### ISSUE TITLE
Chromecast TV not detected

### ISSUE THREAD

**Issue by Mathieu-R** [w3c/remote-playback#117]
Hello,

I was trying to use this api on `Chrome M66` to send audio content on a remote device but it does not detect my `Chromecast tv`.
Other API such as Presentation API detect it.

I was wondering it there's a bug or something else.
Maybe an error in my code.

Btw, if I force with `audioElement.remote.prompt()`, it throws me an error that says: `A prompt is already shown` but that's not the case.

Anyway here's the code that track the device availability : 

```js
// audio is an audio element
monitorRemoteAvailability (audio) {
  return audio.remote.watchAvailability(available => {
    console.log(available);  // false even if my chromecast tv is available
    this.updateChromecastButtonDisplay({available});
  }).catch(_ => {
    // assume remote device is available
    this.updateChromecastButtonDisplay({available: true});
  })
}
```

Thanks for your help.

**Comment by mounirlamouri** [comment]
Thank you for the feedback @Mathieu-R. In general, it's better to use Chromium's bug tracker if you see a bug in Chromium. In your case, it looks a lot like your issue may be related to https://crbug.com/837299 If it's not the case, can you file a new bug using https://crbug.com/new?

**Comment by Mathieu-R** [comment]
Thanks. It does not seem to be related to the existing issus. I filed a new bug.

**Comment by Mathieu-R** [comment]
@mounirlamouri 
Well, I was able to make this demo (https://beaufortfrancois.github.io/sandbox/media/remote-playback.html) work on Chrome stable (and canary) for Android.
I also did my own demo and this works.

The problem in my case is that I use Google shaka-player to stream media. It seems that Remote Playback API does not work with buffer in the src attribute.

**Comment by mounirlamouri** [comment]
At the moment, the Remote Playback API on Chrome Android does not handle MSE videos. It sounds that this may be the issue you are facing here. Can you put the link to the Chromium bug in this issue so we can continue the discussion over there?

**Comment by Mathieu-R** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=843965
