### ISSUE TITLE
Support for TTML and IMSC captions

### ISSUE THREAD

**Issue by chrisn** [w3c/remote-playback#120]
At present, it is not possible to render TTML and IMSC captions with video being presented remotely using the Remote Playback API. Captions are tyically rendered using script with HTML content overlaid over the video. Without native rendering support, we could use the Presentation API to do this, but this introduces the complication of having to communicate the control and state information of the remoted media element over the `PresentationConnection` (see #119).

**Comment by mounirlamouri** [comment]
With the work being done around a generic caption API presented at TPAC and FOMS, we should have a solution for this problem at some point. I do not expect the Remote Playback API to have a custom solution for non-native captions as it's meant to be a quick and simple API.

Please feel free to re-open or leave a comment if that sounds unreasonable.
