### ISSUE TITLE
Allow implementations to drop some requests if they can't be remotely played

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/remote-playback#13]
We need implementations to be able to tell the page that something can't be played remotely because it is not supported by the other end. It can be because of EME, because of audio/video codecs or maybe because of MSE.

I did not think yet of the mechanism but I think having `connect()` reject with some error (like `NotSupported`) could be the right approach.

**Comment by avayvod** [comment]
I covered the case in the <code>connect()</code> algorithm: the promise is rejected with NotSupported when the media source is not supported by the user agent or is a priori not compatible with any supported remote playback device.
