### ISSUE TITLE
example

### ISSUE THREAD

**Issue by ckmilse** [w3c/remote-playback#144]
the feature is interesting.  Could u give me a complete demo.

**Comment by ckmilse** [comment]
The RemotePlayback API is disabled on this platform.

**Comment by anssiko** [comment]
Thanks for your interest. This repository is for specification development related discussions.

Web developers may find e.g. the following resources helpful:

https://developer.mozilla.org/en-US/docs/Web/API/Remote_Playback_API

https://caniuse.com/mdn-api_remoteplayback

https://chromestatus.com/feature/5778318691401728
