### ISSUE TITLE
RemotePlayback.state should have events corresponding to state changes

### ISSUE THREAD

**Issue by avayvod** [w3c/remote-playback#2]
E.g. `onconnected`, `ondisconnected`, etc.
Having an event handler makes sense so that the web developer doesn't have to poll the attribute.
Per-state events vs a single `onstatechange` mostly for consistency with the Presentation API.

**Comment by avayvod** [comment]
`ondisconnected` should have a `reason` attribute to notify if there was an error of some sort or user action or is it due to the page calling something like `stop()` itself.

**Comment by mounirlamouri** [comment]
Having a `statechange` event sgtm. Do we really need an event per state change? Presentation API has details for the `close` event but we don't have a close state here.

**Comment by avayvod** [comment]
The <code>statechange</code> event is present in the spec now. I agree we don't want more complex event structure for a simple API.
