### ISSUE TITLE
remote.onstatechange vs. remote.on{connect,connecting,disconnect}

### ISSUE THREAD

**Issue by markafoltz** [w3c/remote-playback#36]
In the Presentation API, we converted the API from having one statechange event to distinct events for each state, to improve developer ergonomics: fewer if/then/else blocks in a monolithic event handler.

(I can't find the specific GH issue where this was discussed, since I think it was an offshoot of other API discussions. Can dig some more if interested.)

Perhaps the Remote Playback API should do the same:

```
partial interface RemotePlayback : EventTarget {
            attribute EventHandler onconnect;
            attribute EventHandler ondisconnect;
};
```

However, the initial value of `remote.state` does not seem to be defined; that would need to be addressed to determine whether an additional `connecting` event is necessary.

**Comment by hober** [comment]
SGTM.

**Comment by tidoust** [comment]
Discussed at F2F:
http://www.w3.org/2016/05/24-webscreens-minutes.html#item04

**PROPOSED RESOLUTION:** break up the statechange into 3 different events as described in https://github.com/w3c/remote-playback/issues/36#issue-156024443
