### ISSUE TITLE
setupRemotePlayback() called twice in Example 2 and Example 3?

### ISSUE THREAD

**Issue by markafoltz** [w3c/remote-playback#40]
It looks like `setupRemotePlayback()` is called twice when the user clicks remotePlaybackBtn, once in the resolver for `connect()` and again in the `onstatechange` event handler when the state transitions to `connecting`.

Also, you may want to disable remotePlaybackBtn when the state changes to `connecting`, and re-enable it on a transition to `disconnected`.  Maybe this would be done in the setup/stop helper functions?

**Comment by avayvod** [comment]
@mfoltzgoogle, I think that the website would typically just use one or the other example for `setupRemotePlayback`. I implemented the functions in the example to underline they could be reenterable, including your suggestion about hiding/showing the button.

I think addressing issues #36 and #4 should make the examples clearer too.
