### ISSUE TITLE
Implementation guidance for browsers when a media element with controls is remoted

### ISSUE THREAD

**Issue by markafoltz** [w3c/remote-playback#48]
The controls attribute will have the UA render default media controls for the media element [1].  If a media element with controls set is remoted, the spec might want to note that the default controls should be updated accordingly for the remote case (i.e. the attribute is still respected even in remote mode), and possibly give an implementation suggestion like using a poster image in place of the rendered `<video>`.

[1] https://www.w3.org/TR/html5/embedded-content-0.html#attr-media-controls

This issue is related to Issue #46.

**Comment by tidoust** [comment]
See [related discussion at TPAC](http://www.w3.org/2016/09/22-webscreens-minutes#ins20)

Main takeaway is to add a note to recommend that controls should convey the fact that the playback happens remotely. Also discussion suggests to make explicit that local playback of a video that gets remoted should be paused.

**Comment by markafoltz** [comment]
I think the PR captures the conclusions from this issue.  Please reopen if there is something that I missed.
