### ISSUE TITLE
Race between cancelWatchAvailability and disableRemotePlayback

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/remote-playback#53]
According to the specification, calling `cancelWatchAvailability` will reject if `disableRemotePlayback` is true. However, setting `disableRemotePlayback` is not expect to stop watch which means that we might end up in situations where per spec, the callback to watch availability will have to run for ever.

We should either ask that `disableRemotePlayback` cancels watch or that `cancelWatchAvailability` doesn't reject if `disableRemotePlayback`.

In my opinion, we should do the former to stay consist with the spirit of the specification: when `disableRemotePlayback` is set to true, UA is expected to stop remote session. It should also stop watching for availability.

**Comment by mounirlamouri** [comment]
CC @jernoble @avayvod

**Comment by avayvod** [comment]
I agree with Mounir.
