### ISSUE TITLE
Update status section

### ISSUE THREAD

**Issue by anssiko** [w3c/remote-playback#58]
In preparation for the wide review, it would be good to update the SoTD section, clarify the "This document is a work in progress and is subject to change" note to better reflect reality knowing implementations are coming together. Also, note the status of existing issues. My assessment says the remaining open issues are considered minor, except issue #41 that suggests extensions to HTMLMediaElement and HTMLVideoElement interfaces; would be good to note this explicitly to attract further feedback and suggestions during wide review. Let me know if you feel the same.

The reason for updating SoTD is simply to make it easier for people outside this group reading the wide review spec to be informed of the stability and completeness of the spec, and give better feedback.

@tidoust volunteered to address this issue. Thanks!

**Comment by anssiko** [comment]
@tidoust please ping this issue when the status section has been updated accordingly and we'll prepare a snapshot ready for WD publication.

**Comment by tidoust** [comment]
From a timing perspective, note that the group is in-between charters: the charter expired a couple of days ago, the new one has not been officially approved yet. It would be preferable to postpone publication to /TR/ until we have a proper charter. That should be the case by end of this week.

**Comment by tidoust** [comment]
SOTD updated and new WD published at:
https://www.w3.org/TR/2016/WD-remote-playback-20161107/
