### ISSUE TITLE
Getting availability and monitoring list of devices algorithms

### ISSUE THREAD

**Issue by markafoltz** [w3c/remote-playback#59]
Step 8-1 of the getting availability algorithm [1] queues a task to invoke the callback with the availability status, but it's not clear what the value would be if the "monitoring a list" algorithm was not already running. 

As a corollary, the "monitoring a list" algorithm does not need to be started again in step 8-2 if it was already running.  Or is it assumed to run continuously in the background?

Also, in step 2-2 of "monitoring a list", the callback is invoked with a calculated value but the calculation is not defined.  I would assume that you mean the list of available playback devices is non-empty :)

[1] https://w3c.github.io/remote-playback/#getting-the-remote-playback-devices-availability-information

**Comment by avayvod** [comment]
There's a definition for [availability](https://w3c.github.io/remote-playback/#dfn-availability) value for the specific media element. We should define it as empty initially - that would guarantee `false` to be returned with the first callback.

We might rephrase 8-2 to not run the "monitoring a list" algorithm if it's already running.
