### ISSUE TITLE
Make NotFoundError when prompt() is called and availability monitoring is not available optional

### ISSUE THREAD

**Issue by avayvod** [w3c/remote-playback#65]
The step 8 from the ```prompt()``` [algorithm](https://w3c.github.io/remote-playback/#prompt-user-for-changing-remote-playback-state) was inspired by the similar step (10.2) in the Presentation API's ```PresentationRequest.start()``` [algorithm](https://w3c.github.io/presentation-api/#starting-a-presentation).

This step seems problematic to implement when the availability monitoring is not supported by the device. At least on Android the device picker dialog will not hide until user closes it even if devices are not found. Closing the dialog by the browser would be against the current guidelines of using it I assume.

I propose making this step optional.

@mfoltzgoogle - I'm not sure how this works with the Presentation API on desktop (I think on Android it is not supported as well).

**Comment by markafoltz** [comment]
I believe this step is to handle when the user agent has disabled device discovery in a way that won't change over the lifetime of the call to `prompt()`, so the user agent would have no reason to show a dialog anyway.  I don't think we handle this specifically on Chrome for desktop and always show the dialog.

**Comment by mounirlamouri** [comment]
My understanding of step 8 is that the user agent should reject immediately if it knows that the dialog will show no devices. However, the case you present is different because we need to show the dialog and do the discovery and then realize there is nothing.

Is my understanding correct?

**Comment by avayvod** [comment]
Yes, I'm thinking about the case when the background availability monitoring is not available and we have to show the dialog to start active device discovery. We could argue that there's no timeout in this case as user could turn on a device at any moment.

**Comment by mounirlamouri** [comment]
In the case you describe, `prompt()` would hang while the dialog is visible and the `state` will stay `disconnected` which is all fine, right? If the user picks a device, it would switch the `state` to `connecting` and resolve the promise. Otherwise, it would reject the promise with `NotAllowedError`, right?

**Comment by avayvod** [comment]
Ok, one can argue that in the use case I describe above the UA doesn't know if the "list of available remote playback devices..." "...will remain so [empty] before the request for user permission is completed" which makes the step a no-op.
