### ISSUE TITLE
Internationalization considerations

### ISSUE THREAD

**Issue by tidoust** [w3c/remote-playback#66]
It is good practice to evaluate the spec against [internationalization techniques](http://www.w3.org/International/techniques/developing-specs) before requesting horizontal review from the i18n group. Most of these points do not seem to apply to the Remote Playback API though.

It seems useful to take a look at the Presentation API and draw parallels. I think the following i18n-related aspects of the Presentation API may warrant notes in the Remote Playback API spec:

1. The note at the end of [§6.3.2](https://w3c.github.io/presentation-api/#starting-a-presentation) about advertising and using "the locale and intended text direction of the user friendly name" of remote playback devices.
2. The text at the end of [§6.6.1](https://w3c.github.io/presentation-api/#creating-a-receiving-browsing-context) that receiving user agents should fetch resources "with an HTTP Accept-Language header that reflects the language preferences of the controlling user agent". This cannot be normative text in the case of the Remote Playback API because remote playback devices are not a conformance class, but an informative note could perhaps highlight that implementers are encouraged to pass the locale to the remote playback device if possible. Remote playback devices may use that information to select the audio track(s) that get enabled as well for instance. I'm not entirely clear how media playback remoting affects the enabled status of media tracks that compose the media stream, but that seems to be in scope of issue #41.

**Comment by tomoyukilabs** [comment]
In addition to the items suggested above, I would like to suggest that rendering text tracks (e.g. WebVTT) by a remote playback device might be affected by the locale if the device would support text tracks, especially in the case of CJK languages. This concern might be similar to https://github.com/w3c/presentation-api/issues/218#issuecomment-155362449. As well as user agent's locale, [`srclang` attribute of `<track>` element](https://www.w3.org/TR/html/semantics-embedded-content.html#dom-htmltrackelement-srclang) should be passed to the remote playback device, if possible. Of course, this also cannot be normative text.

**Comment by anssiko** [comment]
@tidoust, could you craft a PR per your suggestion? Note that I just submitted a PR #99 that addresses @tomoyukilabs's  comment as well as fixes the another i18n comment #70.

**Comment by anssiko** [comment]
Fixed with #100
