### ISSUE TITLE
[Privacy] Request to disable monitoring when disableRemotePlayback is set

### ISSUE THREAD

**Issue by markafoltz** [w3c/remote-playback#80]
https://lists.w3.org/Archives/Public/public-privacy/2017JanMar/0009.html

> 1)   In the section “Disabling remote playback”, consider to add the requirement that the monitoring of devices must not occur if the feature is disabled by the user, thus “If the disableRemotePlayback attribute is present on the media element, the user agent MUST NOT monitor availability, play the media remotely or present any UI to do so.  

Should update steps to ensure that monitoring is stopped when the set of availability callbacks has been emptied?

**Comment by avayvod** [comment]
Given there might be user agent specific UI (default controls or toolbar) depending on the monitoring, I don't think we can require the UA to stop all monitoring when the set of availability callbacks is empty.
It's similar for the ```disableRemotePlayback``` attribute. There might be other media elements loaded on some page or other browser feature depending on the monitoring (like tab casting).
The information is not exposed to the page via the specific element if its availability callbacks set is empty and/or if it has ```disableRemotePlayback``` set.

**Comment by markafoltz** [comment]
If `disableRemotePlayback` is set on a media element, won't that also disable remote playback UI on the default controls/toolbar?

I agree that an empty set of availability callbacks shouldn't disable monitoring though.

We may want to clarify that there if there is a browser level control to disable background monitoring, how the API should behave.

**Comment by avayvod** [comment]
Definitely not on the user agent's toolbar as it's unlikely refers to one single element.

```disableRemotePlayback``` is to prevent remote playback of a certain media element, not availability monitoring although it does disable the media element specific availability related methods for consistency.

I'm not sure clarifying how browser features / settings affect the API is necessary as long as it affects it in a non-website breaking way like reporting no devices available and being consistent with it.

**Comment by markafoltz** [comment]
On re-reading, this issue will be closed by implementing the changes proposed in Issue #84.

The original suggestion is not correctly formed as discussed here; `disableRemotePlayback` applies to a single media element, not to background monitoring as a whole or any browser level controls that might require it.

I'm closing this, any further discussion of API behavior can continue in #84 or the forthcoming PR.
