### ISSUE TITLE
Produce a preliminary implementation report

### ISSUE THREAD

**Issue by anssiko** [w3c/remote-playback#87]
To be able to publish a Candidate Recommendation #73, we need a preliminary implementation report similarly to the [Presentation API test results] (see test results column).

@avayvod @mounirlamouri, are you happy with the current coverage of the [Remote Playback API test suite]? (You added idlharness tests that were initially missing, is [TODO] up to date?)

@Honry could perhaps help you produce a preliminary implementation report using the Chrome for Android implementation https://crbug.com/578833 if you so prefer, and/or help update the test suite if some tests are still missing.

[Presentation API test results]: https://www.w3.org/wiki/Second_Screen/Implementation_Status#Tests
[Remote Playback API test suite]: https://github.com/w3c/web-platform-tests/tree/master/remote-playback
[TODO]: https://github.com/w3c/web-platform-tests/tree/master/remote-playback#todo

**Comment by mounirlamouri** [comment]
I've sent a PR to update the README. The tests in the repo are the ones avayvod@ and I uploaded from Blink. I wouldn't say I'm happy because a lot of tests require to interact with the remote device and we can't do that from WPT but it's better than nothing.

**Comment by Honry** [comment]
@avayvod, @mounirlamouri, please tell me if anything I can help. :)

**Comment by anssiko** [comment]
@mounirlamouri if you'd like @Honry to take a stab at the implementation report, he'd appreciate instructions on how to setup the test environment. @Honry has developed manual tests for other APIs such as [battery-status] in the past.

[battery-status]: https://github.com/w3c/web-platform-tests/tree/master/battery-status

**Comment by mounirlamouri** [comment]
I guess something you can start with is looking at the tests that we have [in Blink](https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/media/remoteplayback/) using our internal test infrastructure.

The issue with this API is that you will have to use a Chrome Cast compatible device to test the API on Chrome but another browser might not support Chrome Cast. The test preconditions will have to start with something a bit hand-wavy like "Have a device compatible with the browser on your WiFi". Because only Chrome (maybe other Chrome-based browsers) has an implementation for this at the moment, it would be hard to be clearer.

**Comment by Honry** [comment]
@mounirlamouri, I glance over both Chromium Layout tests and wpt tests, almost all the tests are about exceptions and I can easily generate the test report. If you need please tell me which platforms should be covered.

>The issue with this API is that you will have to use a Chrome Cast compatible device to test the API on Chrome but another browser might not support Chrome Cast.

This is the issue [Presentation API](https://github.com/w3c/web-platform-tests/tree/master/presentation-api) had ever encountered, but now they have much more sufficient test suite, maybe we can consult them.

**Comment by mounirlamouri** [comment]
At the moment, only Chrome Android supports the Remote Playback API so I guess you should only do a report on this platform?

Following a pattern similar to Presentation API would make sense. I wonder how much we can use this as an inspiration as the Remote Playback API is fairly simpler.

**Comment by avayvod** [comment]
Chrome Desktop also exposes the API but doesn't support any remote playback devices yet.

**Comment by Honry** [comment]
Actually the test result of current test suite are all pass on both Chrome for Android and Desktop, I just committed the report at https://github.com/w3c/test-results/pull/102. PTAL.

**Comment by Honry** [comment]
>Following a pattern similar to Presentation API would make sense. I wonder how much we can use this as an inspiration as the Remote Playback API is fairly simpler.

@mounirlamouri, let's talk about the issue in this thread: https://github.com/w3c/remote-playback/issues/92
