### ISSUE TITLE
Remote playback device capabilities not always a subset of local playback device's

### ISSUE THREAD

**Issue by anssiko** [w3c/remote-playback#88]
https://github.com/w3c/remote-playback/issues/41#issuecomment-301596793:

>The remote playback device capabilities might not be always a subset of those of the local playback device. The cases when something is not working locally but can work remotely might be worth looking into and adding a note about too.

Should research and document such capabilities to see how to best reflect that in the spec.

**Comment by anssiko** [comment]
There are two classes of interoperability issues discussed in #41:

* a feature X is not working locally, but can work remotely
* a feature X is not working remotely, but can work locally

This issue is about the former. The issue #41 is (mainly) about the latter.

The text we put in place for the purposes of the CR publication in the [Status of This Document][1] captures the broader interoperability issue, but I still see merit in being explicit in these two classes of issues, since the solutions to them are likely different. 

Let's discuss the possible solutions to the "not working locally, but can work remotely" issue in here.

[1]: https://w3c.github.io/presentation-api/#status-of-this-document

**Comment by mounirlamouri** [comment]
Closing issue per TPAC F2F resolution.
